/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
// UUIDs for the HM-10 (replace with the correct UUIDs if different)
String serviceUuid = "0000ffe0-0000-1000-8000-00805f9b34fb";
String txUuid =
    "0000ffe1-0000-1000-8000-00805f9b34fb"; // Tx characteristic UUID for writing
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
/// DO NOT CHANGE ANYTHING HERE !!
